// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:508066845399:web:6260bbb8379a94b653d692',
    messagingSenderId: '508066845399',
    projectId: 'vector-dee4b',
    authDomain: 'vector-dee4b.firebaseapp.com',
    storageBucket: 'vector-dee4b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:508066845399:android:7c00558a1aa2c6e453d692',
    messagingSenderId: '508066845399',
    projectId: 'vector-dee4b',
    storageBucket: 'vector-dee4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT-fXpk-bnW0H5a0-KWuOo0gnrAkx8pYU',
    appId: '1:508066845399:ios:9d801e0696eda17653d692',
    messagingSenderId: '508066845399',
    projectId: 'vector-dee4b',
    storageBucket: 'vector-dee4b.firebasestorage.app',
    iosBundleId: 'com.example.vector',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT-fXpk-bnW0H5a0-KWuOo0gnrAkx8pYU',
    appId: '1:508066845399:ios:9d801e0696eda17653d692',
    messagingSenderId: '508066845399',
    projectId: 'vector-dee4b',
    storageBucket: 'vector-dee4b.firebasestorage.app',
    iosBundleId: 'com.example.vector',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArlukPCYMzpcWCjRDuLUSag3Nxmmgyksk',
    appId: '1:508066845399:web:c23911ce277b69e653d692',
    messagingSenderId: '508066845399',
    projectId: 'vector-dee4b',
    authDomain: 'vector-dee4b.firebaseapp.com',
    storageBucket: 'vector-dee4b.firebasestorage.app',
  );
}
